joint_limits:
  gripper_motorup_joint:
    has_position_limits: true
    min_position: -10.9
    max_position:  10.9
    has_velocity_limits: true
    max_velocity: 20.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: false
    has_effort_limits: false
    max_effort: 20.0
    angle_wraparound: true # should be ignored, has position limits
  
  gripper_motordown_joint:
    has_position_limits: true
    min_position: -10.9
    max_position:  10.9
    has_velocity_limits: true
    max_velocity: 20.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: false
    has_effort_limits: false
    max_effort: 20.0
    angle_wraparound: true # should be ignored, has position limits
    
#gripper_motorup_joint:
#    has_position_limits: false
#    has_velocity_limits: true
#    max_velocity: 27.27
#    has_acceleration_limits: false
#    max_acceleration: 27.27
#    has_jerk_limits: false
#    has_effort_limits: false
  
#gripper_motordown_joint:
#    has_position_limits: false
#    has_velocity_limits: true
#    max_velocity: 27.27
#    has_acceleration_limits: false
#    max_acceleration: 27.27
#    has_jerk_limits: false
#    has_effort_limits: false

  
