robotnik_base_hw:
  use_rosparam_joint_limits: false
  joint_limits:
    rear_axle_joint:
      has_position_limits: false
      min_position: 0.0
      max_position: 1.0
      has_velocity_limits: true
      max_velocity: 100.0
      has_acceleration_limits: false
      max_acceleration: 5.0
      has_jerk_limits: false
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 100
