robotnik_base_hw:
  port: /dev/pcan32

  # Summit rubber wheels: 0.22, Summit omni wheels: 0.25, RB1: 0.1524 
  diameter_wheel: 0.1524
  # 24V motors: 12.52, 48V motors: 9.56, RB1 Accelerated: 7.5 (9.56?)
  gearbox_ratio: 21.9
  # Be carefull if motors don't have enconders and you put motors_enconder: true speed will increase x 4000
  motors_encoder: false
  motors_encoder_factor: 4000

  joint_name: [rear_axle_joint]
  joint_can_id: [1]
  joint_type: [eff]
  joint_home_offset: [0]
  joint_spin: [1]

generic_hw_control_loop:
  loop_hz: 300 
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
     - rear_axle_joint
   
     
