battery_estimation:
    # Function definition f(x) = a * ln(num_val) + b
    a_charging: 0.6213557428
    b_charging: 23.8321319164
    # Function definition f(x) = a*num_val² + b*num_val + c
    a_discharging: -0.000000304852291409409
    b_discharging: 0.0005258623
    c_discharging: 26.246426097

    # Number of values on each excel
    values_charging: 768
    values_discharging: 3463

    # Max and min time (B column)
    max_charging: 1549967370.58795
    min_charging: 1549955856.98818
    max_discharging: 1549679181.30976
    min_discharging: 1549627213.52789
