battery_estimation:
    # Function definition f(x) = a * ln(num_val) + b
    a_charging: 1.340530228
    b_charging: 45.7277431294
    # Function definition f(x) = a*num_val² + b*num_val + c
    a_discharging: -0.000000829459724028744
    b_discharging: 0.000613416
    c_discharging: 53.3000865103

    # Number of values on each excel
    values_charging: 821
    values_discharging: 2463

    # Max and min time (B column)
    max_charging: 1540373589.01044
    min_charging: 1540361279.67107
    max_discharging: 1540413548.79694
    min_discharging: 1540376590.83684
