joint_limits:
  rb1_base_left_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27   # 3 m/s = 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  rb1_base_right_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
#  joint_back_left_wheel:
#    has_position_limits: false
#    has_velocity_limits: true
#    max_velocity: 27.27
#    has_acceleration_limits: false
#    max_acceleration: 27.27
#    has_jerk_limits: false
#    has_effort_limits: false
  
#  joint_back_right_wheel:
#    has_position_limits: false
#    has_velocity_limits: true
#    max_velocity: 27.27
#    has_acceleration_limits: false
#    max_acceleration: 27.27
#    has_jerk_limits: false
#    has_effort_limits: false

  
